version: '3'
services:
  db:
    image: mysql:5.7.8
    environment:
      - MYSQL_ROOT_PASSWORD=ryouchin0729
    volumes:
      - datavol:/var/lib/mysql
      - ./mysql-confd:/etc/conf.d
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://db
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  datavol:
